### ISSUE TITLE
[Question] 'fetch_html exception status 403: 'Forbidden''. It's that my network problem?

### ISSUE THREAD

**Issue by Moeuin** [trickerer01/RV#13]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

'fetch_html exception status 403: 'Forbidden''. It's that my network problem? its same problem when i use proxy. thanks

### Provide verbose output that demonstrates the problem (use --log-level trace)

```shell
eg:
C:\Users\SAM\RV\src>python pages.py -pages 9999 -search_art nyl -search_rule_art any -path F:/Nyl -quality 1080p
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
RV ver 1.8.493
Command-line args: pages.py -pages 9999 -search_art nyl -search_rule_art any -path F:/Nyl -quality 1080p
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
fetch_html exception status 403: 'Forbidden'
Warning: catched KeyboardInterrupt/SystemExit...
```

**Comment by trickerer** [comment]
Yes it has something to do with network but you your network connection necessarily.
RV website is protected by ddos-guard and usually this isn't a problem, you may get one or two of 403 errors for no apparent reason, they aren't even considered a serious problem and they don't count for connection retries - you just have to wait them out. But sometimes it may take like 100+ retries. It has something to do with protection algorithm I guess, like the website is under attack or something.
Try to wait, if it doesn't resolve itself then tell me the region of your proxy or, if it's a transparent one - yours, so I can try to reproduce. And try a different proxy.

Also you're not the only one: #12. Right now the whole european network is suffering some kind of problem and people in whole countries receive error 504 when trying to connect. More info on RV website discord which you can find invintation link of its front page

**Comment by Moeuin** [comment]
> Reference in new

thanks a lot, It seems that folks have the same problem.
