### ISSUE TITLE
Is it possible to add a feature to download my favorite videos?

### ISSUE THREAD

**Issue by Knockoi** [trickerer01/RV#15]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

I wish I could download all my my favorites.

**Comment by trickerer01** [comment]
https://github.com/trickerer01/RV/commit/95dd01ab877b650ae1ed629c1f3319d116e33841

Note that this new argument only accepts user id (integer)
