### ISSUE TITLE
[Question] How can I download a user made playlist with this?

### ISSUE THREAD

**Issue by aUser7** [trickerer01/RV#5]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

I really don't understand how I can download playlists with this. Where do I find the playlist id? If I use the playlist_id option with the playlist id from the URL it does not work. :/

**Comment by trickerer01** [comment]
Playlist ids and names can be found in a list file located in 'playlists' folder https://github.com/trickerer01/RV/tree/master/5playlists
You may use either `-playlist_id` or `-playlist_name` argument:
- `python pages.py -playlist_name <name> -pages <number> -path <path>`
- `python pages.py -playlist_id <number> -pages <number> -path <path>`

Important: playlists file updates about once a month so newer playlists might be missing. Last update was October 8th. Playlists file is only for reference, adding new playlist info to the file will not make RV recognize it; if this is urgent I can instruct you on how to add new playlist manually.

**Comment by aUser7** [comment]
Yea would be cool to know how I can add playlists manually 👍

**Comment by trickerer01** [comment]
Firstly, update to the last version.
Then add this code at tagger.py line 13792 (after info dictionaries get decoded):
```python
PLA_NUMS_DECODED.update({
    'playlist_name1': 'playlist_id1',
    'playlist_name2': 'playlist_id2',
})
```
playlist_name and playlist_id are both strings, only id is numeric (no videos count).

Example from existing playlists:
```python
PLA_NUMS_DECODED.update({
    'jinxmix': '74107',
    'jobless': '22249',
})
```

**Comment by aUser7** [comment]
I got it to work, thanks. 👍👍
