### ISSUE TITLE
[Question] ISSUE_TITLE

### ISSUE THREAD

**Issue by 972513547** [trickerer01/RV#6]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

Hello, I always pop up when using it
ModuleNotFoundError: No module named 'aiofile'
I can't use it properly. I'm a new Python user, please forgive my foolish question

**Comment by trickerer01** [comment]
Like with most python apps, you need to install required python packages to be able to use it.

https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#using-requirements-files
- `python3 -m pip install -r requirements.txt`

The same page explains the usage of virtual environments which is always a good idea to consider before installing any packages for a new project you create or use.

**Comment by trickerer01** [comment]
Closing as completed
