### ISSUE TITLE
[Question] How to download by model

### ISSUE THREAD

**Issue by chienhao10** [trickerer01/RV#7]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

I am not sure how search or tag works in Rule34video, but i was able to find contents i want by using google, and provide me url like this: https://rule34video.com/models/hydrafxx/
after check on each video, it seems different vod can be upload by different users, and artist can be more than 1 as well. (i was able to download by uploader ID, but it has too many unwanted contents).

How do i only download the contents from the url (https://rule34video.com/models/hydrafxx/) with multi pages.

**Comment by trickerer** [comment]
Invoke `python pages.py --help`:
```
  -search #string       Native search using string query (matching any word). Spaces must be replced with '-'. Ex. 'after-hours'
  -search_tag #tag[,tag...]
  -search_art #artist[,artist...]
  -search_cat #catergory[,category...]
                        Native search by tag(s) / artist(s) / category(ies). Spaces must be replced with '_', concatenate with ','. Example: '-search_tag 1girl,side_view -search_art
                        artist_name -search_cat category_name'. Note that search obeys 'AND' rule: search string AND ANY_OF/ALL the tags AND ANY_OF/ALL the artists AND ANY_OF/ALL the
                        categories
```
Use `-search_art <ARTISTNAME>`. It uses native website search API and is only available via `pages` module

**Comment by chienhao10** [comment]
> Invoke `python pages.py --help`:
> 
> ```
>   -search #string       Native search using string query (matching any word). Spaces must be replced with '-'. Ex. 'after-hours'
>   -search_tag #tag[,tag...]
>   -search_art #artist[,artist...]
>   -search_cat #catergory[,category...]
>                         Native search by tag(s) / artist(s) / category(ies). Spaces must be replced with '_', concatenate with ','. Example: '-search_tag 1girl,side_view -search_art
>                         artist_name -search_cat category_name'. Note that search obeys 'AND' rule: search string AND ANY_OF/ALL the tags AND ANY_OF/ALL the artists AND ANY_OF/ALL the
>                         categories
> ```
> 
> Use `-search_art <ARTISTNAME>`. It uses native website search API and is only available via `pages` module

hi thx for reply. Yes, i have also tired with that command. However, it seems getting more than i need. F
or example 'https://rule34video.com/models/hydrafxx/' this url shows there are only 4 pages. but if i use below
```
pages.py -search_art hydrafxx -pages 5

response:
page 1...
page 2...
page 3...
page 4...
page 5...
Scanning dest folder...
Found 138 file(s)
```

it will get me 5 pages of contents, shouldn't it only have 4 pages of contents?

**Comment by trickerer** [comment]
Oh, that one.
#4

There is no option to dowload artist pages currently since it has less coverage overall. On the other hand, it seems like these extra videos are all compilations. If you exclude compilation tags only original 92 videos from author's 4 pages will be downloaded (out of 507). It takes more time of course, how much - depends on desired video quality. Currently only 2 compilation tags exist: `pmv` and `compilation`.
Maybe later I'll add an option for artist pages, as I can see there are more and more reused content videos cluttering search results.

<details><summary>Short log</summary>
<p>

```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Command-line args: P:/RV/src/pages.py -path P:/!!dwn/test1 -start 1 -pages 99 -quality 720p -dmode touch -search_art hydrafxx -pmv -compilation
Extracted max page: 22
page 1...
page 2...
...
page 22... (this is the last page!)
reached parsed max page, page scan completed

Ok! 507 ids (+0 filtered out), bound 3048733 to 3330794. Working...

This will take at least 468 seconds!

Saving<touch> rv_3048733.mp4 0.00 Mb to rv_3048733_(+299)_Ada X Leon - HydraFXX_(Ada_Wong,Leon_Kennedy,hydrafxx,straight)_720p.mp4
Saving<touch> rv_3048746.mp4 0.00 Mb to rv_3048746_(+400)_Mercy Being Moist - HydraFXX_(Mercy,hydrafxx,overwatch,squirt,straight)_720p.mp4
Saving<touch> rv_3048824.mp4 0.00 Mb to rv_3048824_(+159)_Tracer X D.va Beach - HydraFXX_(Dva,Tracer,hydrafxx,lesbian,overwatch,straight)_720p.mp4
Saving<touch> rv_3048825.mp4 0.00 Mb to rv_3048825_(+270)_Claire Sheriff Blowjob - HydraFXX_(hydrafxx,oral,straight)_720p.mp4
...
Warning: cannot find quality '720p' for rv_3054134.mp4, selecting '480p'
Saving<touch> rv_3054134.mp4 0.00 Mb to rv_3054134_(+655)_Loba - HydraFXX_(1boy,1girl,Loba,hydrafxx,straight)_480p.mp4
...
Video rv_3056003.mp4 contains excluded tag 'pmv'. Skipped!
Video rv_3056003.mp4 contains excluded tag 'compilation'. Skipped!
Info: video rv_3056003.mp4 is filtered out by extra tags, skipping...
Video rv_3056064.mp4 contains excluded tag 'pmv'. Skipped!
Video rv_3056064.mp4 contains excluded tag 'compilation'. Skipped!
Info: video rv_3056064.mp4 is filtered out by extra tags, skipping...
Video rv_3056065.mp4 contains excluded tag 'pmv'. Skipped!
Video rv_3056065.mp4 contains excluded tag 'compilation'. Skipped!
Info: video rv_3056065.mp4 is filtered out by extra tags, skipping...


Done. 92 / 507+0 file(s) downloaded, 0+0 already existed, 415 skipped

Process finished with exit code 0
```

</p>
</details>

**Comment by trickerer01** [comment]
https://github.com/trickerer01/RV/commit/d7265adb153cb9325c70d45bbf2025cb82034948
https://github.com/trickerer01/RV/commit/dd4c16d55d6593384599f9c694f23fd057fcbd00
